### PR TITLE
Allow PHP 8.3

### PR DESCRIPTION
**Pull request by eivydas**
Depends on [#259](https://github.com/Webador/SlmQueue/pull/259)

### CODE REVIEW

**Comment by eivydas** [comment]
Depends on [#259](https://github.com/Webador/SlmQueue/pull/259)

**Comment by roelvanduijnhoven** [comment]
Thanks @eivydas. I've just cut a new release for SlmQueue. Can you adapt this PR accordingly, and let me know?

**Comment by eivydas** [comment]
@roelvanduijnhoven pull request was updated

**Comment by roelvanduijnhoven** [comment]
Deployed!

**Pull request merged**
